name: Build Spring Boot with Maven
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**/*'
jobs:
  build_and_verify:
    name: Run Merge checks
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: 'maven'
          
      - name: Permitir execução do mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B clean verify --no-transfer-progress

      - name: Build Docker image
        run: docker build -t spring-6-auth-server:latest .

      - name: Tag Docker image para GHCR
        run: docker tag spring-6-auth-server ghcr.io/flavioandreaz/spring-6-auth-server:latest

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image para GHCR
        run: docker push ghcr.io/flavioandreaz/spring-6-auth-server:latest

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            ./target/surefire